odyssey.eventlog.dynamodb.ephemeral-prefix=ephemeral:
odyssey.eventlog.dynamodb.channel-prefix=channel:
odyssey.eventlog.dynamodb.broadcast-prefix=broadcast:
odyssey.eventlog.dynamodb.table-name=odyssey_events
odyssey.eventlog.dynamodb.auto-create-table=false
odyssey.eventlog.dynamodb.ttl-seconds=86400
