odyssey.eventlog.rabbitmq.ephemeral-prefix=ephemeral:
odyssey.eventlog.rabbitmq.channel-prefix=channel:
odyssey.eventlog.rabbitmq.broadcast-prefix=broadcast:
odyssey.eventlog.rabbitmq.host=localhost
odyssey.eventlog.rabbitmq.port=5552
odyssey.eventlog.rabbitmq.max-age-seconds=3600
odyssey.eventlog.rabbitmq.max-length-bytes=524288000
