odyssey.eventlog.cassandra.ephemeral-prefix=ephemeral:
odyssey.eventlog.cassandra.channel-prefix=channel:
odyssey.eventlog.cassandra.broadcast-prefix=broadcast:
odyssey.eventlog.cassandra.default-ttl=24h
odyssey.eventlog.cassandra.auto-create-schema=false
