package org.jwcarman.odyssey.redis;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import io.lettuce.core.api.sync.RedisCommands;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.jwcarman.odyssey.core.OdysseyStream;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class RedisOdysseyStreamRegistryTest {

  private static final String STREAM_PREFIX = "odyssey:";
  private static final long KEEP_ALIVE = 30_000;
  private static final long SSE_TIMEOUT = 0;
  private static final long MAX_LEN = 100_000;
  private static final int MAX_LAST_N = 500;
  private static final long EPHEMERAL_TTL = 300;
  private static final long CHANNEL_TTL = 3600;
  private static final long BROADCAST_TTL = 86400;

  @Mock private RedisCommands<String, String> commands;
  @Mock private PubSubNotificationListener listener;

  private RedisOdysseyStreamRegistry registry;

  @BeforeEach
  void setUp() {
    registry =
        new RedisOdysseyStreamRegistry(
            commands,
            listener,
            STREAM_PREFIX,
            KEEP_ALIVE,
            SSE_TIMEOUT,
            MAX_LEN,
            MAX_LAST_N,
            EPHEMERAL_TTL,
            CHANNEL_TTL,
            BROADCAST_TTL);
  }

  @Test
  void ephemeralReturnsStreamWithAutoGeneratedKey() {
    OdysseyStream stream = registry.ephemeral();

    assertNotNull(stream);
    assertTrue(stream.getStreamKey().startsWith(STREAM_PREFIX + "ephemeral:"));
  }

  @Test
  void ephemeralKeyContainsUuid() {
    OdysseyStream stream = registry.ephemeral();

    String key = stream.getStreamKey();
    String uuid = key.substring((STREAM_PREFIX + "ephemeral:").length());
    assertDoesNotThrow(() -> java.util.UUID.fromString(uuid));
  }

  @Test
  void ephemeralSetsTtlOnStreamKey() {
    OdysseyStream stream = registry.ephemeral();

    verify(commands).expire(stream.getStreamKey(), EPHEMERAL_TTL);
  }

  @Test
  void ephemeralRegistersFanoutWithListener() {
    OdysseyStream stream = registry.ephemeral();

    verify(listener).registerFanout(eq(stream.getStreamKey()), any(TopicFanout.class));
  }

  @Test
  void eachEphemeralCallReturnsDistinctInstance() {
    OdysseyStream first = registry.ephemeral();
    OdysseyStream second = registry.ephemeral();

    assertNotSame(first, second);
    assertNotEquals(first.getStreamKey(), second.getStreamKey());
  }

  @Test
  void channelReturnsStreamWithCorrectKey() {
    OdysseyStream stream = registry.channel("user:123");

    assertEquals(STREAM_PREFIX + "channel:user:123", stream.getStreamKey());
  }

  @Test
  void channelSetsTtlOnStreamKey() {
    registry.channel("user:123");

    verify(commands).expire(STREAM_PREFIX + "channel:user:123", CHANNEL_TTL);
  }

  @Test
  void channelRegistersFanoutWithListener() {
    registry.channel("user:123");

    verify(listener).registerFanout(eq(STREAM_PREFIX + "channel:user:123"), any(TopicFanout.class));
  }

  @Test
  void repeatedChannelCallsReturnSameInstance() {
    OdysseyStream first = registry.channel("user:123");
    OdysseyStream second = registry.channel("user:123");

    assertSame(first, second);
  }

  @Test
  void differentChannelNamesReturnDifferentInstances() {
    OdysseyStream first = registry.channel("user:123");
    OdysseyStream second = registry.channel("user:456");

    assertNotSame(first, second);
  }

  @Test
  void broadcastReturnsStreamWithCorrectKey() {
    OdysseyStream stream = registry.broadcast("announcements");

    assertEquals(STREAM_PREFIX + "broadcast:announcements", stream.getStreamKey());
  }

  @Test
  void broadcastSetsTtlOnStreamKey() {
    registry.broadcast("announcements");

    verify(commands).expire(STREAM_PREFIX + "broadcast:announcements", BROADCAST_TTL);
  }

  @Test
  void broadcastRegistersFanoutWithListener() {
    registry.broadcast("announcements");

    verify(listener)
        .registerFanout(eq(STREAM_PREFIX + "broadcast:announcements"), any(TopicFanout.class));
  }

  @Test
  void repeatedBroadcastCallsReturnSameInstance() {
    OdysseyStream first = registry.broadcast("announcements");
    OdysseyStream second = registry.broadcast("announcements");

    assertSame(first, second);
  }

  @Test
  void differentBroadcastNamesReturnDifferentInstances() {
    OdysseyStream first = registry.broadcast("announcements");
    OdysseyStream second = registry.broadcast("alerts");

    assertNotSame(first, second);
  }

  @Test
  void channelAndBroadcastWithSameNameReturnDifferentInstances() {
    OdysseyStream channel = registry.channel("news");
    OdysseyStream broadcast = registry.broadcast("news");

    assertNotSame(channel, broadcast);
  }

  @Test
  void zeroTtlSkipsExpireCall() {
    RedisOdysseyStreamRegistry noTtlRegistry =
        new RedisOdysseyStreamRegistry(
            commands,
            listener,
            STREAM_PREFIX,
            KEEP_ALIVE,
            SSE_TIMEOUT,
            MAX_LEN,
            MAX_LAST_N,
            0,
            0,
            0);

    noTtlRegistry.broadcast("test");

    verify(commands, never()).expire(anyString(), anyLong());
  }
}
