package org.jwcarman.odyssey.engine;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.jwcarman.odyssey.core.OdysseyStream;
import org.jwcarman.odyssey.spi.OdysseyEventLog;
import org.jwcarman.odyssey.spi.OdysseyStreamNotifier;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class DefaultOdysseyStreamRegistryTest {

  private static final long KEEP_ALIVE = 30_000;
  private static final long SSE_TIMEOUT = 0;
  private static final int MAX_LAST_N = 500;

  @Mock private OdysseyEventLog eventLog;
  @Mock private OdysseyStreamNotifier notifier;

  private DefaultOdysseyStreamRegistry registry;

  @BeforeEach
  void setUp() {
    registry =
        new DefaultOdysseyStreamRegistry(eventLog, notifier, KEEP_ALIVE, SSE_TIMEOUT, MAX_LAST_N);
  }

  @Test
  void ephemeralReturnsStreamWithAutoGeneratedKey() {
    when(eventLog.ephemeralKey()).thenReturn("ephemeral:test-uuid");

    OdysseyStream stream = registry.ephemeral();

    assertNotNull(stream);
    assertTrue(stream.getStreamKey().startsWith("ephemeral:"));
  }

  @Test
  void ephemeralKeyContainsUuid() {
    String uuid = java.util.UUID.randomUUID().toString();
    when(eventLog.ephemeralKey()).thenReturn("ephemeral:" + uuid);

    OdysseyStream stream = registry.ephemeral();

    String key = stream.getStreamKey();
    String extractedUuid = key.substring("ephemeral:".length());
    assertDoesNotThrow(() -> java.util.UUID.fromString(extractedUuid));
  }

  @Test
  void eachEphemeralCallReturnsDistinctInstance() {
    when(eventLog.ephemeralKey())
        .thenReturn("ephemeral:" + java.util.UUID.randomUUID())
        .thenReturn("ephemeral:" + java.util.UUID.randomUUID());

    OdysseyStream first = registry.ephemeral();
    OdysseyStream second = registry.ephemeral();

    assertNotSame(first, second);
    assertNotEquals(first.getStreamKey(), second.getStreamKey());
  }

  @Test
  void channelReturnsStreamWithCorrectKey() {
    when(eventLog.channelKey("user:123")).thenReturn("channel:user:123");

    OdysseyStream stream = registry.channel("user:123");

    assertEquals("channel:user:123", stream.getStreamKey());
  }

  @Test
  void repeatedChannelCallsReturnSameInstance() {
    when(eventLog.channelKey("user:123")).thenReturn("channel:user:123");

    OdysseyStream first = registry.channel("user:123");
    OdysseyStream second = registry.channel("user:123");

    assertSame(first, second);
  }

  @Test
  void differentChannelNamesReturnDifferentInstances() {
    when(eventLog.channelKey("user:123")).thenReturn("channel:user:123");
    when(eventLog.channelKey("user:456")).thenReturn("channel:user:456");

    OdysseyStream first = registry.channel("user:123");
    OdysseyStream second = registry.channel("user:456");

    assertNotSame(first, second);
  }

  @Test
  void broadcastReturnsStreamWithCorrectKey() {
    when(eventLog.broadcastKey("announcements")).thenReturn("broadcast:announcements");

    OdysseyStream stream = registry.broadcast("announcements");

    assertEquals("broadcast:announcements", stream.getStreamKey());
  }

  @Test
  void repeatedBroadcastCallsReturnSameInstance() {
    when(eventLog.broadcastKey("announcements")).thenReturn("broadcast:announcements");

    OdysseyStream first = registry.broadcast("announcements");
    OdysseyStream second = registry.broadcast("announcements");

    assertSame(first, second);
  }

  @Test
  void differentBroadcastNamesReturnDifferentInstances() {
    when(eventLog.broadcastKey("announcements")).thenReturn("broadcast:announcements");
    when(eventLog.broadcastKey("alerts")).thenReturn("broadcast:alerts");

    OdysseyStream first = registry.broadcast("announcements");
    OdysseyStream second = registry.broadcast("alerts");

    assertNotSame(first, second);
  }

  @Test
  void channelAndBroadcastWithSameNameReturnDifferentInstances() {
    when(eventLog.channelKey("news")).thenReturn("channel:news");
    when(eventLog.broadcastKey("news")).thenReturn("broadcast:news");

    OdysseyStream channel = registry.channel("news");
    OdysseyStream broadcast = registry.broadcast("news");

    assertNotSame(channel, broadcast);
  }

  @Test
  void registrySubscribesToNotifier() {
    verify(notifier).subscribe(any());
  }
}
