/*
 * Copyright © 2026 James Carman
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jwcarman.odyssey.engine;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.jwcarman.odyssey.core.OdysseyEvent;
import org.jwcarman.odyssey.core.OdysseyStream;
import org.jwcarman.substrate.core.Journal;
import org.jwcarman.substrate.core.JournalFactory;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import tools.jackson.databind.ObjectMapper;

@ExtendWith(MockitoExtension.class)
class DefaultOdysseyStreamRegistryTest {

  private static final long KEEP_ALIVE = 30_000;
  private static final long SSE_TIMEOUT = 0;

  @Mock private JournalFactory journalFactory;
  @Mock private Journal<OdysseyEvent> journal;

  private DefaultOdysseyStreamRegistry registry;

  @BeforeEach
  void setUp() {
    registry =
        new DefaultOdysseyStreamRegistry(
            journalFactory, new ObjectMapper(), KEEP_ALIVE, SSE_TIMEOUT);
  }

  @Test
  void ephemeralReturnsStreamWithAutoGeneratedKey() {
    when(journalFactory.create(startsWith("ephemeral:"), eq(OdysseyEvent.class)))
        .thenReturn(journal);
    lenient().when(journal.key()).thenReturn("substrate:journal:ephemeral:test-uuid");

    OdysseyStream stream = registry.ephemeral();

    assertNotNull(stream);
    assertTrue(stream.getStreamKey().contains("ephemeral:"));
  }

  @Test
  void eachEphemeralCallReturnsDistinctInstance() {
    Journal<OdysseyEvent> journal2 = mock();
    when(journalFactory.create(startsWith("ephemeral:"), eq(OdysseyEvent.class)))
        .thenReturn(journal)
        .thenReturn(journal2);
    lenient().when(journal.key()).thenReturn("substrate:journal:ephemeral:uuid1");
    lenient().when(journal2.key()).thenReturn("substrate:journal:ephemeral:uuid2");

    OdysseyStream first = registry.ephemeral();
    OdysseyStream second = registry.ephemeral();

    assertNotSame(first, second);
    assertNotEquals(first.getStreamKey(), second.getStreamKey());
  }

  @Test
  void channelReturnsStream() {
    when(journalFactory.create("channel:user:123", OdysseyEvent.class)).thenReturn(journal);
    lenient().when(journal.key()).thenReturn("substrate:journal:channel:user:123");

    OdysseyStream stream = registry.channel("user:123");

    assertNotNull(stream);
  }

  @Test
  void repeatedChannelCallsReturnSameInstance() {
    when(journalFactory.create("channel:user:123", OdysseyEvent.class)).thenReturn(journal);
    lenient().when(journal.key()).thenReturn("substrate:journal:channel:user:123");

    OdysseyStream first = registry.channel("user:123");
    OdysseyStream second = registry.channel("user:123");

    assertSame(first, second);
  }

  @Test
  void differentChannelNamesReturnDifferentInstances() {
    Journal<OdysseyEvent> journal2 = mock();
    when(journalFactory.create("channel:user:123", OdysseyEvent.class)).thenReturn(journal);
    when(journalFactory.create("channel:user:456", OdysseyEvent.class)).thenReturn(journal2);
    lenient().when(journal.key()).thenReturn("substrate:journal:channel:user:123");
    lenient().when(journal2.key()).thenReturn("substrate:journal:channel:user:456");

    OdysseyStream first = registry.channel("user:123");
    OdysseyStream second = registry.channel("user:456");

    assertNotSame(first, second);
  }

  @Test
  void broadcastReturnsStream() {
    when(journalFactory.create("broadcast:announcements", OdysseyEvent.class)).thenReturn(journal);
    lenient().when(journal.key()).thenReturn("substrate:journal:broadcast:announcements");

    OdysseyStream stream = registry.broadcast("announcements");

    assertNotNull(stream);
  }

  @Test
  void repeatedBroadcastCallsReturnSameInstance() {
    when(journalFactory.create("broadcast:announcements", OdysseyEvent.class)).thenReturn(journal);
    lenient().when(journal.key()).thenReturn("substrate:journal:broadcast:announcements");

    OdysseyStream first = registry.broadcast("announcements");
    OdysseyStream second = registry.broadcast("announcements");

    assertSame(first, second);
  }

  @Test
  void differentBroadcastNamesReturnDifferentInstances() {
    Journal<OdysseyEvent> journal2 = mock();
    when(journalFactory.create("broadcast:announcements", OdysseyEvent.class)).thenReturn(journal);
    when(journalFactory.create("broadcast:alerts", OdysseyEvent.class)).thenReturn(journal2);
    lenient().when(journal.key()).thenReturn("substrate:journal:broadcast:announcements");
    lenient().when(journal2.key()).thenReturn("substrate:journal:broadcast:alerts");

    OdysseyStream first = registry.broadcast("announcements");
    OdysseyStream second = registry.broadcast("alerts");

    assertNotSame(first, second);
  }

  @Test
  void channelAndBroadcastWithSameNameReturnDifferentInstances() {
    Journal<OdysseyEvent> journal2 = mock();
    when(journalFactory.create("channel:news", OdysseyEvent.class)).thenReturn(journal);
    when(journalFactory.create("broadcast:news", OdysseyEvent.class)).thenReturn(journal2);
    lenient().when(journal.key()).thenReturn("substrate:journal:channel:news");
    lenient().when(journal2.key()).thenReturn("substrate:journal:broadcast:news");

    OdysseyStream channel = registry.channel("news");
    OdysseyStream broadcast = registry.broadcast("news");

    assertNotSame(channel, broadcast);
  }

  @Test
  void streamReturnsCachedInstance() {
    when(journalFactory.create("odyssey:channel:cached", OdysseyEvent.class)).thenReturn(journal);
    lenient().when(journal.key()).thenReturn("substrate:journal:odyssey:channel:cached");

    OdysseyStream first = registry.stream("odyssey:channel:cached");
    OdysseyStream second = registry.stream("odyssey:channel:cached");

    assertSame(first, second);
  }

  @Test
  void streamCreatesNewInstanceForNewKey() {
    when(journalFactory.create("odyssey:channel:newkey", OdysseyEvent.class)).thenReturn(journal);
    lenient().when(journal.key()).thenReturn("substrate:journal:odyssey:channel:newkey");

    OdysseyStream stream = registry.stream("odyssey:channel:newkey");

    assertNotNull(stream);
  }
}
