package org.jwcarman.odyssey.engine;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.jwcarman.odyssey.core.OdysseyStream;
import org.jwcarman.odyssey.spi.OdysseyEventLog;
import org.jwcarman.odyssey.spi.OdysseyStreamNotifier;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class DefaultOdysseyStreamRegistryTest {

  private static final String STREAM_PREFIX = "odyssey:";
  private static final long KEEP_ALIVE = 30_000;
  private static final long SSE_TIMEOUT = 0;
  private static final int MAX_LAST_N = 500;

  @Mock private OdysseyEventLog eventLog;
  @Mock private OdysseyStreamNotifier notifier;

  private DefaultOdysseyStreamRegistry registry;

  @BeforeEach
  void setUp() {
    registry =
        new DefaultOdysseyStreamRegistry(
            eventLog, notifier, STREAM_PREFIX, KEEP_ALIVE, SSE_TIMEOUT, MAX_LAST_N);
  }

  @Test
  void ephemeralReturnsStreamWithAutoGeneratedKey() {
    OdysseyStream stream = registry.ephemeral();

    assertNotNull(stream);
    assertTrue(stream.getStreamKey().startsWith(STREAM_PREFIX + "ephemeral:"));
  }

  @Test
  void ephemeralKeyContainsUuid() {
    OdysseyStream stream = registry.ephemeral();

    String key = stream.getStreamKey();
    String uuid = key.substring((STREAM_PREFIX + "ephemeral:").length());
    assertDoesNotThrow(() -> java.util.UUID.fromString(uuid));
  }

  @Test
  void eachEphemeralCallReturnsDistinctInstance() {
    OdysseyStream first = registry.ephemeral();
    OdysseyStream second = registry.ephemeral();

    assertNotSame(first, second);
    assertNotEquals(first.getStreamKey(), second.getStreamKey());
  }

  @Test
  void channelReturnsStreamWithCorrectKey() {
    OdysseyStream stream = registry.channel("user:123");

    assertEquals(STREAM_PREFIX + "channel:user:123", stream.getStreamKey());
  }

  @Test
  void repeatedChannelCallsReturnSameInstance() {
    OdysseyStream first = registry.channel("user:123");
    OdysseyStream second = registry.channel("user:123");

    assertSame(first, second);
  }

  @Test
  void differentChannelNamesReturnDifferentInstances() {
    OdysseyStream first = registry.channel("user:123");
    OdysseyStream second = registry.channel("user:456");

    assertNotSame(first, second);
  }

  @Test
  void broadcastReturnsStreamWithCorrectKey() {
    OdysseyStream stream = registry.broadcast("announcements");

    assertEquals(STREAM_PREFIX + "broadcast:announcements", stream.getStreamKey());
  }

  @Test
  void repeatedBroadcastCallsReturnSameInstance() {
    OdysseyStream first = registry.broadcast("announcements");
    OdysseyStream second = registry.broadcast("announcements");

    assertSame(first, second);
  }

  @Test
  void differentBroadcastNamesReturnDifferentInstances() {
    OdysseyStream first = registry.broadcast("announcements");
    OdysseyStream second = registry.broadcast("alerts");

    assertNotSame(first, second);
  }

  @Test
  void channelAndBroadcastWithSameNameReturnDifferentInstances() {
    OdysseyStream channel = registry.channel("news");
    OdysseyStream broadcast = registry.broadcast("news");

    assertNotSame(channel, broadcast);
  }

  @Test
  void registrySubscribesToNotifier() {
    verify(notifier).subscribe(any());
  }
}
