/*
 * Copyright © 2026 James Carman
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jwcarman.odyssey.core;

import java.time.Instant;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * An immutable event published to an {@link OdysseyStream}. Each event corresponds to a single SSE
 * message delivered to subscribers.
 *
 * <p>Events are constructed using the {@link Builder}:
 *
 * <pre>{@code
 * OdysseyEvent event = OdysseyEvent.builder()
 *     .streamKey("odyssey:channel:user:123")
 *     .eventType("notification")
 *     .payload("{\"message\": \"hello\"}")
 *     .timestamp(Instant.now())
 *     .build();
 * }</pre>
 *
 * <p>The {@code metadata} map is defensively copied and made unmodifiable. Passing {@code null} for
 * metadata results in an empty map.
 *
 * @param id the event ID, generated by the {@link org.jwcarman.odyssey.spi.OdysseyEventLog}
 *     implementation; used as the SSE {@code id:} field for reconnect support
 * @param streamKey the full key of the stream this event belongs to
 * @param eventType the SSE {@code event:} field, or {@code null} for the default event type
 * @param payload the SSE {@code data:} field, typically JSON
 * @param timestamp the wall-clock time when the event was published
 * @param metadata optional caller-supplied key-value pairs stored alongside the event
 */
public record OdysseyEvent(
    String id,
    String streamKey,
    String eventType,
    String payload,
    Instant timestamp,
    Map<String, String> metadata) {

  /** Compact constructor that defensively copies and makes the metadata map unmodifiable. */
  public OdysseyEvent {
    metadata =
        metadata == null ? Map.of() : Collections.unmodifiableMap(new LinkedHashMap<>(metadata));
  }

  /**
   * Creates a new builder for constructing an {@link OdysseyEvent}.
   *
   * @return a new builder instance
   */
  public static Builder builder() {
    return new Builder();
  }

  /** A fluent builder for constructing {@link OdysseyEvent} instances. */
  public static final class Builder {

    private String id;
    private String streamKey;
    private String eventType;
    private String payload;
    private Instant timestamp;
    private Map<String, String> metadata = Map.of();

    private Builder() {}

    /**
     * Sets the event ID.
     *
     * @param id the event ID
     * @return this builder
     */
    public Builder id(String id) {
      this.id = id;
      return this;
    }

    /**
     * Sets the stream key this event belongs to.
     *
     * @param streamKey the stream key
     * @return this builder
     */
    public Builder streamKey(String streamKey) {
      this.streamKey = streamKey;
      return this;
    }

    /**
     * Sets the SSE event type.
     *
     * @param eventType the event type, or {@code null} for the default type
     * @return this builder
     */
    public Builder eventType(String eventType) {
      this.eventType = eventType;
      return this;
    }

    /**
     * Sets the event payload.
     *
     * @param payload the event data, typically JSON
     * @return this builder
     */
    public Builder payload(String payload) {
      this.payload = payload;
      return this;
    }

    /**
     * Sets the event timestamp.
     *
     * @param timestamp the wall-clock time of the event
     * @return this builder
     */
    public Builder timestamp(Instant timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    /**
     * Sets optional metadata for the event.
     *
     * @param metadata key-value pairs to store alongside the event
     * @return this builder
     */
    public Builder metadata(Map<String, String> metadata) {
      this.metadata = metadata;
      return this;
    }

    /**
     * Builds a new {@link OdysseyEvent} from this builder's state.
     *
     * @return the constructed event
     */
    public OdysseyEvent build() {
      return new OdysseyEvent(id, streamKey, eventType, payload, timestamp, metadata);
    }
  }
}
