odyssey.eventlog.hazelcast.ephemeral-prefix=odyssey:ephemeral:
odyssey.eventlog.hazelcast.channel-prefix=odyssey:channel:
odyssey.eventlog.hazelcast.broadcast-prefix=odyssey:broadcast:
odyssey.eventlog.hazelcast.ringbuffer-capacity=100000
odyssey.eventlog.hazelcast.ringbuffer-ttl=1h
