odyssey.eventlog.postgresql.ephemeral-prefix=ephemeral:
odyssey.eventlog.postgresql.channel-prefix=channel:
odyssey.eventlog.postgresql.broadcast-prefix=broadcast:
odyssey.eventlog.postgresql.max-len=100000
odyssey.eventlog.postgresql.auto-create-schema=false
