odyssey.eventlog.nats.ephemeral-prefix=ephemeral:
odyssey.eventlog.nats.channel-prefix=channel:
odyssey.eventlog.nats.broadcast-prefix=broadcast:
odyssey.eventlog.nats.url=nats://localhost:4222
odyssey.eventlog.nats.stream-name=ODYSSEY
odyssey.eventlog.nats.max-age=1h
odyssey.eventlog.nats.max-messages=100000
