odyssey.eventlog.mongodb.ephemeral-prefix=ephemeral:
odyssey.eventlog.mongodb.channel-prefix=channel:
odyssey.eventlog.mongodb.broadcast-prefix=broadcast:
odyssey.eventlog.mongodb.collection-name=odyssey_events
odyssey.eventlog.mongodb.ttl=24h
